// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod fb {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum NetworkFilterOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NetworkFilter<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NetworkFilter<'a> {
  type Inner = NetworkFilter<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> NetworkFilter<'a> {
  pub const VT_MASK: flatbuffers::VOffsetT = 4;
  pub const VT_OPT_DOMAINS: flatbuffers::VOffsetT = 6;
  pub const VT_OPT_NOT_DOMAINS: flatbuffers::VOffsetT = 8;
  pub const VT_PATTERNS: flatbuffers::VOffsetT = 10;
  pub const VT_MODIFIER_OPTION: flatbuffers::VOffsetT = 12;
  pub const VT_HOSTNAME: flatbuffers::VOffsetT = 14;
  pub const VT_TAG: flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NetworkFilter { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NetworkFilterArgs<'args>
  ) -> flatbuffers::WIPOffset<NetworkFilter<'bldr>> {
    let mut builder = NetworkFilterBuilder::new(_fbb);
    if let Some(x) = args.tag { builder.add_tag(x); }
    if let Some(x) = args.hostname { builder.add_hostname(x); }
    if let Some(x) = args.modifier_option { builder.add_modifier_option(x); }
    if let Some(x) = args.patterns { builder.add_patterns(x); }
    if let Some(x) = args.opt_not_domains { builder.add_opt_not_domains(x); }
    if let Some(x) = args.opt_domains { builder.add_opt_domains(x); }
    builder.add_mask(args.mask);
    builder.finish()
  }

  pub fn unpack(&self) -> NetworkFilterT {
    let mask = self.mask();
    let opt_domains = self.opt_domains().map(|x| {
      x.into_iter().collect()
    });
    let opt_not_domains = self.opt_not_domains().map(|x| {
      x.into_iter().collect()
    });
    let patterns = self.patterns().map(|x| {
      x.iter().map(|s| s.to_string()).collect()
    });
    let modifier_option = self.modifier_option().map(|x| {
      x.to_string()
    });
    let hostname = self.hostname().map(|x| {
      x.to_string()
    });
    let tag = self.tag().map(|x| {
      x.to_string()
    });
    NetworkFilterT {
      mask,
      opt_domains,
      opt_not_domains,
      patterns,
      modifier_option,
      hostname,
      tag,
    }
  }

  #[inline]
  pub fn mask(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(NetworkFilter::VT_MASK, Some(0)).unwrap()}
  }
  #[inline]
  pub fn opt_domains(&self) -> Option<flatbuffers::Vector<'a, u16>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(NetworkFilter::VT_OPT_DOMAINS, None)}
  }
  #[inline]
  pub fn opt_not_domains(&self) -> Option<flatbuffers::Vector<'a, u16>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(NetworkFilter::VT_OPT_NOT_DOMAINS, None)}
  }
  #[inline]
  pub fn patterns(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(NetworkFilter::VT_PATTERNS, None)}
  }
  #[inline]
  pub fn modifier_option(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(NetworkFilter::VT_MODIFIER_OPTION, None)}
  }
  #[inline]
  pub fn hostname(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(NetworkFilter::VT_HOSTNAME, None)}
  }
  #[inline]
  pub fn tag(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(NetworkFilter::VT_TAG, None)}
  }
}

impl flatbuffers::Verifiable for NetworkFilter<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("mask", Self::VT_MASK, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("opt_domains", Self::VT_OPT_DOMAINS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("opt_not_domains", Self::VT_OPT_NOT_DOMAINS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("patterns", Self::VT_PATTERNS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("modifier_option", Self::VT_MODIFIER_OPTION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("hostname", Self::VT_HOSTNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("tag", Self::VT_TAG, false)?
     .finish();
    Ok(())
  }
}
pub struct NetworkFilterArgs<'a> {
    pub mask: u32,
    pub opt_domains: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub opt_not_domains: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub patterns: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub modifier_option: Option<flatbuffers::WIPOffset<&'a str>>,
    pub hostname: Option<flatbuffers::WIPOffset<&'a str>>,
    pub tag: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for NetworkFilterArgs<'a> {
  #[inline]
  fn default() -> Self {
    NetworkFilterArgs {
      mask: 0,
      opt_domains: None,
      opt_not_domains: None,
      patterns: None,
      modifier_option: None,
      hostname: None,
      tag: None,
    }
  }
}

pub struct NetworkFilterBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NetworkFilterBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_mask(&mut self, mask: u32) {
    self.fbb_.push_slot::<u32>(NetworkFilter::VT_MASK, mask, 0);
  }
  #[inline]
  pub fn add_opt_domains(&mut self, opt_domains: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkFilter::VT_OPT_DOMAINS, opt_domains);
  }
  #[inline]
  pub fn add_opt_not_domains(&mut self, opt_not_domains: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkFilter::VT_OPT_NOT_DOMAINS, opt_not_domains);
  }
  #[inline]
  pub fn add_patterns(&mut self, patterns: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkFilter::VT_PATTERNS, patterns);
  }
  #[inline]
  pub fn add_modifier_option(&mut self, modifier_option: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkFilter::VT_MODIFIER_OPTION, modifier_option);
  }
  #[inline]
  pub fn add_hostname(&mut self, hostname: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkFilter::VT_HOSTNAME, hostname);
  }
  #[inline]
  pub fn add_tag(&mut self, tag: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkFilter::VT_TAG, tag);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NetworkFilterBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NetworkFilterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NetworkFilter<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NetworkFilter<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NetworkFilter");
      ds.field("mask", &self.mask());
      ds.field("opt_domains", &self.opt_domains());
      ds.field("opt_not_domains", &self.opt_not_domains());
      ds.field("patterns", &self.patterns());
      ds.field("modifier_option", &self.modifier_option());
      ds.field("hostname", &self.hostname());
      ds.field("tag", &self.tag());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct NetworkFilterT {
  pub mask: u32,
  pub opt_domains: Option<Vec<u16>>,
  pub opt_not_domains: Option<Vec<u16>>,
  pub patterns: Option<Vec<String>>,
  pub modifier_option: Option<String>,
  pub hostname: Option<String>,
  pub tag: Option<String>,
}
impl Default for NetworkFilterT {
  fn default() -> Self {
    Self {
      mask: 0,
      opt_domains: None,
      opt_not_domains: None,
      patterns: None,
      modifier_option: None,
      hostname: None,
      tag: None,
    }
  }
}
impl NetworkFilterT {
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>
  ) -> flatbuffers::WIPOffset<NetworkFilter<'b>> {
    let mask = self.mask;
    let opt_domains = self.opt_domains.as_ref().map(|x|{
      _fbb.create_vector(x)
    });
    let opt_not_domains = self.opt_not_domains.as_ref().map(|x|{
      _fbb.create_vector(x)
    });
    let patterns = self.patterns.as_ref().map(|x|{
      let w: Vec<_> = x.iter().map(|s| _fbb.create_string(s)).collect();_fbb.create_vector(&w)
    });
    let modifier_option = self.modifier_option.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let hostname = self.hostname.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let tag = self.tag.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    NetworkFilter::create(_fbb, &NetworkFilterArgs{
      mask,
      opt_domains,
      opt_not_domains,
      patterns,
      modifier_option,
      hostname,
      tag,
    })
  }
}
pub enum NetworkFilterListOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NetworkFilterList<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NetworkFilterList<'a> {
  type Inner = NetworkFilterList<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> NetworkFilterList<'a> {
  pub const VT_SORTED_HASHES: flatbuffers::VOffsetT = 4;
  pub const VT_SORTED_NETWORK_FILTERS: flatbuffers::VOffsetT = 6;
  pub const VT_UNIQUE_DOMAINS_HASHES: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NetworkFilterList { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NetworkFilterListArgs<'args>
  ) -> flatbuffers::WIPOffset<NetworkFilterList<'bldr>> {
    let mut builder = NetworkFilterListBuilder::new(_fbb);
    if let Some(x) = args.unique_domains_hashes { builder.add_unique_domains_hashes(x); }
    if let Some(x) = args.sorted_network_filters { builder.add_sorted_network_filters(x); }
    if let Some(x) = args.sorted_hashes { builder.add_sorted_hashes(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> NetworkFilterListT {
    let sorted_hashes = {
      let x = self.sorted_hashes();
      x.into_iter().collect()
    };
    let sorted_network_filters = {
      let x = self.sorted_network_filters();
      x.iter().map(|t| t.unpack()).collect()
    };
    let unique_domains_hashes = {
      let x = self.unique_domains_hashes();
      x.into_iter().collect()
    };
    NetworkFilterListT {
      sorted_hashes,
      sorted_network_filters,
      unique_domains_hashes,
    }
  }

  #[inline]
  pub fn sorted_hashes(&self) -> flatbuffers::Vector<'a, u64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u64>>>(NetworkFilterList::VT_SORTED_HASHES, None).unwrap()}
  }
  #[inline]
  pub fn sorted_network_filters(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<NetworkFilter<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<NetworkFilter>>>>(NetworkFilterList::VT_SORTED_NETWORK_FILTERS, None).unwrap()}
  }
  #[inline]
  pub fn unique_domains_hashes(&self) -> flatbuffers::Vector<'a, u64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u64>>>(NetworkFilterList::VT_UNIQUE_DOMAINS_HASHES, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for NetworkFilterList<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u64>>>("sorted_hashes", Self::VT_SORTED_HASHES, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<NetworkFilter>>>>("sorted_network_filters", Self::VT_SORTED_NETWORK_FILTERS, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u64>>>("unique_domains_hashes", Self::VT_UNIQUE_DOMAINS_HASHES, true)?
     .finish();
    Ok(())
  }
}
pub struct NetworkFilterListArgs<'a> {
    pub sorted_hashes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u64>>>,
    pub sorted_network_filters: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<NetworkFilter<'a>>>>>,
    pub unique_domains_hashes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u64>>>,
}
impl<'a> Default for NetworkFilterListArgs<'a> {
  #[inline]
  fn default() -> Self {
    NetworkFilterListArgs {
      sorted_hashes: None, // required field
      sorted_network_filters: None, // required field
      unique_domains_hashes: None, // required field
    }
  }
}

pub struct NetworkFilterListBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NetworkFilterListBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sorted_hashes(&mut self, sorted_hashes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkFilterList::VT_SORTED_HASHES, sorted_hashes);
  }
  #[inline]
  pub fn add_sorted_network_filters(&mut self, sorted_network_filters: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<NetworkFilter<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkFilterList::VT_SORTED_NETWORK_FILTERS, sorted_network_filters);
  }
  #[inline]
  pub fn add_unique_domains_hashes(&mut self, unique_domains_hashes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkFilterList::VT_UNIQUE_DOMAINS_HASHES, unique_domains_hashes);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NetworkFilterListBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NetworkFilterListBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NetworkFilterList<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, NetworkFilterList::VT_SORTED_HASHES,"sorted_hashes");
    self.fbb_.required(o, NetworkFilterList::VT_SORTED_NETWORK_FILTERS,"sorted_network_filters");
    self.fbb_.required(o, NetworkFilterList::VT_UNIQUE_DOMAINS_HASHES,"unique_domains_hashes");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NetworkFilterList<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NetworkFilterList");
      ds.field("sorted_hashes", &self.sorted_hashes());
      ds.field("sorted_network_filters", &self.sorted_network_filters());
      ds.field("unique_domains_hashes", &self.unique_domains_hashes());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct NetworkFilterListT {
  pub sorted_hashes: Vec<u64>,
  pub sorted_network_filters: Vec<NetworkFilterT>,
  pub unique_domains_hashes: Vec<u64>,
}
impl Default for NetworkFilterListT {
  fn default() -> Self {
    Self {
      sorted_hashes: Default::default(),
      sorted_network_filters: Default::default(),
      unique_domains_hashes: Default::default(),
    }
  }
}
impl NetworkFilterListT {
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>
  ) -> flatbuffers::WIPOffset<NetworkFilterList<'b>> {
    let sorted_hashes = Some({
      let x = &self.sorted_hashes;
      _fbb.create_vector(x)
    });
    let sorted_network_filters = Some({
      let x = &self.sorted_network_filters;
      let w: Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();_fbb.create_vector(&w)
    });
    let unique_domains_hashes = Some({
      let x = &self.unique_domains_hashes;
      _fbb.create_vector(x)
    });
    NetworkFilterList::create(_fbb, &NetworkFilterListArgs{
      sorted_hashes,
      sorted_network_filters,
      unique_domains_hashes,
    })
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `NetworkFilterList`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_network_filter_list_unchecked`.
pub fn root_as_network_filter_list(buf: &[u8]) -> Result<NetworkFilterList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<NetworkFilterList>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `NetworkFilterList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_network_filter_list_unchecked`.
pub fn size_prefixed_root_as_network_filter_list(buf: &[u8]) -> Result<NetworkFilterList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<NetworkFilterList>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `NetworkFilterList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_network_filter_list_unchecked`.
pub fn root_as_network_filter_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<NetworkFilterList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<NetworkFilterList<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `NetworkFilterList` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_network_filter_list_unchecked`.
pub fn size_prefixed_root_as_network_filter_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<NetworkFilterList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<NetworkFilterList<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a NetworkFilterList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `NetworkFilterList`.
pub unsafe fn root_as_network_filter_list_unchecked(buf: &[u8]) -> NetworkFilterList {
  flatbuffers::root_unchecked::<NetworkFilterList>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed NetworkFilterList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `NetworkFilterList`.
pub unsafe fn size_prefixed_root_as_network_filter_list_unchecked(buf: &[u8]) -> NetworkFilterList {
  flatbuffers::size_prefixed_root_unchecked::<NetworkFilterList>(buf)
}
#[inline]
pub fn finish_network_filter_list_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<NetworkFilterList<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_network_filter_list_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<NetworkFilterList<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod fb

